image: openjdk:8

pipelines:
  branches:
    master:
      - step:
          caches:
            - gradle
            - gradlewrapper
          script:
            - bash ./gradlew build --no-daemon jacocoTestReport sonarqube publish -Dsonar.projectKey=chumakac_mset-core -Dsonar.organization=chumakac-bitbucket -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -PawsSecret=$AWS_SECRET

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
